[store]
path = "./store.db"
background_task_frequency_hours = 24
pplns_ttl_days = 7

[stratum]
hostname = "0.0.0.0"
port = 3333
start_difficulty = 1
minimum_difficulty = 0
# The bitcoin address to use for first jobs when there are no
# shares. The default provided is the 256 Foundation address.
bootstrap_address = "tb1qv52has55hpe2vdqm2lfpsqvdl8djjfjukp9kpw"
# Any donation amount for developers to be sent to donation address. Default no donation.
# donation_address = "<your donation address here>"
# In basis points, 1% = 100 basis points. Default 0
# donation = 50
# Any fee amount for node/hydrapool provider to be sent to fee address. Default no fee.
# fee_address = "<your fee address here>"
# In basis points, 1% = 100 basis points. Default 0
# fee = 200
zmqpubhashblock = "tcp://127.0.0.1:28334"
# The network can be "main", "testnet4" or "signet"
network = "signet"
version_mask = "1fffe000"
# The difficulty multiplier defines the window size for calculating payout proportions
# See https://github.com/p2poolv2/p2poolv2/wiki/Difficult-Multiplier on how to choose this
difficulty_multiplier = 1.0
# Add a pool signature, if you want. Comment out the line if you want
# to mine anonymous blocks. This signature is only used to show others
# how large your pool is, if you are running private, there is no need
# to add a pool signature. Maximum length 16 bytes.
# Note: If [coinbase_tag] section is configured, pool_signature will be automatically
# composed from the coinbase_tag fields. Otherwise, you can set it manually.
pool_signature = "hydrapool"

[coinbase_tag]
# Optional coinbase tag metadata fields for signature composition
# All fields are optional. If provided, they will be combined into the pool_signature
# following the standard format: [TAG]|[[type][len][value]] for each field
# pool = "mypool"
miner = "majoal0"
software = "hydrapool"
# website = "hydrapool.org"
# custom = ""

[bitcoinrpc]
# RPC credentials are loaded from env vars
url = "http://127.0.0.1:38332"
username = "user"
password = "pass"

[logging]
# Specify a file path for the log file, if no log file is specified, console logging will be used
# file = "./logs/p2pool.log"
# Set a log level. The supported levels are debug, info, warn and error.
level = "info"
# Pool, user and worker stats are backed up for aggregates across pool restarts in this directory.
stats_dir = "./logs/stats"

[api]
hostname = "0.0.0.0"
port = 46884
# Optional authentication credentials
#auth_user = "hydrapool"
# auth_token is of the format salt:password-hmac. Use can hydrapool_cli gen-auth to generate a token.
#auth_token = "0d74058f74ad3b6768493cedb5e9492b$2a2599d5f4003c291e141762d0e43808cfd932f04a8260e94c375d1574599dbf"
